name: polishCLR_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - merqury
  - meryl
  - parallel
  - pbmm2
  - pbgcpp
  - freebayes
  - bcftools
  - samtools
  - bwa-mem2

